// Corpus de frases. {nombre} se sustituye por el nombre del perfil. El titulo de cada corpus esta en i18n (corpus.<clave>).

export const CORPUS = {
  curioso: {
    frases: [
      "El caballo es la única pieza de ajedrez que puede saltar sobre otras.",
      "Un tablero de ajedrez tiene 64 casillas: 32 claras y 32 oscuras.",
      "La dama se mueve como una torre y un alfil al mismo tiempo.",
      "El jaque mate del pastor se hace en solo cuatro jugadas.",
      "En ajedrez, el rey nunca se captura: se le da jaque mate.",
      "Cada jugador empieza con ocho peones y dos torres.",
      "Pikachu es de tipo eléctrico y evoluciona a Raichu.",
      "Charmander evoluciona a Charmeleon y después a Charizard.",
      "Bulbasaur, Charmander y Squirtle son los iniciales de Kanto.",
      "Un Pokémon de tipo agua tiene ventaja contra uno de tipo fuego.",
      "Snorlax duerme casi todo el día y bloquea el camino.",
      "Eevee puede evolucionar en muchas formas distintas.",
      "La luz del Sol tarda unos ocho minutos en llegar a la Tierra.",
      "Júpiter es el planeta más grande del sistema solar.",
      "Un año luz es la distancia que recorre la luz en un año.",
      "La Luna está a unos 384 mil kilómetros de la Tierra.",
      "Saturno tiene anillos hechos de hielo y rocas.",
      "Un agujero negro atrapa hasta la luz; por eso no se ve.",
      "Marte se ve rojo por el óxido de hierro de su suelo.",
      "La Vía Láctea es la galaxia donde vivimos.",
      "Los números primos solo se dividen entre uno y entre sí mismos.",
      "Dos elevado a diez es 1024.",
      "La mediana es el valor que queda justo en medio de los datos.",
      "El promedio de 2, 4 y 9 es 5.",
      "Si lanzas una moneda cien veces, saldrá cara unas cincuenta.",
      "Siete por ocho son cincuenta y seis.",
      "Un gráfico de barras compara cantidades de un vistazo.",
      "A {nombre} le encantan los nuggets con salsa de barbacoa.",
      "Una pizza grande se corta en ocho rebanadas.",
      "{nombre} dice que la mejor pizza es la de pepperoni.",
      "Los peluches de {nombre} duermen en fila sobre la cama.",
      "{nombre} quiere quedarse despierto hasta ver las estrellas.",
      "Irse a dormir tarde solo vale cuando hay lluvia de meteoros.",
      "Escribir con el teclado es más rápido que con la mano.",
      "¿Cuántas lunas tiene Júpiter? Más de noventa.",
      "El gran maestro pensó diez minutos y movió el peón.",
      "Un cohete necesita ir a 28 mil kilómetros por hora para orbitar.",
      "La probabilidad de sacar un seis con un dado es de uno entre seis.",
    ],
  },
  es: {
    frases: [
      "El dron despegó al amanecer y recorrió los predios de agave antes del calor.",
      "La niña dibujó un pingüino azul en la última página del cuaderno.",
      "Cada ortomosaico pesa varios gigas y tarda horas en procesarse.",
      "Mañana revisamos las hileras del lote norte con el equipo de campo.",
      "El café de la olla huele a canela y a piloncillo recién hervido.",
      "No hay prisa: el código que no se prueba no está terminado.",
      "Las jacarandas tiñen de morado las calles de Guadalajara cada marzo.",
      "¿Quién dejó la puerta del taller abierta durante la tormenta?",
      "El servidor respondió en doce milisegundos y nadie se dio cuenta.",
      "Un buen teclado se nota cuando dejas de pensar en él.",
      "La impresora 3D terminó la pieza a las tres de la mañana sin fallar.",
      "Hoy toca medir antes de afirmar, y afirmar solo lo medido.",
      "Los murciélagos polinizan el agave cuando florece el quiote.",
      "El respaldo nocturno terminó en verde por primera vez en semanas.",
      "Ella corrigió el mapa a mano porque el GPS marcaba diez metros de error.",
      "Apunta la fecha exacta; \"hace poco\" no sirve de nada en un mes.",
      "El viento del norte trajo polvo y una tarde entera sin señal.",
      "Escribir rápido no vale si después hay que borrar la mitad.",
      "La función devolvió una lista vacía y el reporte salió en blanco.",
      "Vamos a cenar tacos de barbacoa cerca del mercado viejo.",
      "El ñu cruzó el río mientras el guía señalaba la orilla opuesta.",
      "Cuesta más explicar un atajo que aprenderse el camino largo.",
      "Si la prueba toca producción, no es una prueba: es un incidente.",
      "Las abejas zumbaban entre las flores de calabaza bajo el sol de julio.",
      "Reinicia el servicio, pero primero mira qué trabajo está corriendo.",
      "Nunca subestimes un cable USB barato en una máquina importante.",
      "Con dos monitores sobra espacio; con uno curvo sobra cuello.",
      "Pásame la llave inglesa que está junto a la caja de tornillos.",
      "Aquel examen fue fácil porque estudiamos juntos la noche anterior.",
    ],
  },
  en: {
    frases: [
      "The quick brown fox jumps over the lazy dog near the riverbank.",
      "Measure twice, cut once, and keep the receipt just in case.",
      "A test that talks to production is an incident, not a test.",
      "The drone finished the survey before the afternoon wind picked up.",
      "Please commit early, push often, and never force on a shared branch.",
      "Her keyboard clicked softly while the rain tapped on the window.",
      "Small functions with clear names age better than clever ones.",
      "We watched the sunrise from the roof with cold coffee and warm bread.",
      "The backup finished at midnight and the log turned green at last.",
      "If it is not written down, it did not happen in a month from now.",
      "The printer stalled at ninety percent and then quietly resumed.",
      "Good tools disappear; you only notice the ones that get in the way.",
      "Six geese flew low over the frozen lake just before dusk.",
      "Type the sentence exactly as shown, including every comma and period.",
      "Nobody remembers the fast feature; everybody remembers the lost data.",
    ],
  },
};
